In [4]:
import pandas as pd

months = [
    "Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
    "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"
]

avg_temp = [-5, -4, 1, 10, 16, 19, 21, 20, 14, 8, 1, -3]

precip = [38, 36, 34, 36, 46, 56, 60, 48, 36, 36, 44, 44]

df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip
})

df.head()

  month  avg_temp  precip
0   Січ        -5      38
1   Лют        -4      36
2   Бер         1      34
3   Кві        10      36
4   Тра        16      46

In [5]:
df.shape
df.dtypes

month       object
avg_temp     int64
precip       int64
dtype: object

In [6]:
print(df)
print(df.index)

   month  avg_temp  precip
0    Січ        -5      38
1    Лют        -4      36
2    Бер         1      34
3    Кві        10      36
4    Тра        16      46
5    Чер        19      56
6    Лип        21      60
7    Сер        20      48
8    Вер        14      36
9    Жов         8      36
10   Лис         1      44
11   Гру        -3      44
RangeIndex(start=0, stop=12, step=1)

In [7]:
df_by_month = df.set_index("month")

print(df_by_month.loc["Лип"])

avg_temp    21
precip      60
Name: Лип, dtype: int64

In [8]:
df = df_by_month.reset_index()

print(df)

   month  avg_temp  precip
0    Січ        -5      38
1    Лют        -4      36
2    Бер         1      34
3    Кві        10      36
4    Тра        16      46
5    Чер        19      56
6    Лип        21      60
7    Сер        20      48
8    Вер        14      36
9    Жов         8      36
10   Лис         1      44
11   Гру        -3      44

In [9]:
df.index = range(1, 13)

print(df.loc[1:6, "avg_temp"])

1    -5
2    -4
3     1
4    10
5    16
6    19
Name: avg_temp, dtype: int64

In [10]:
print(df.iloc[0:6, 1])

1    -5
2    -4
3     1
4    10
5    16
6    19
Name: avg_temp, dtype: int64

In [11]:
print(df[["month", "precip"]])

   month  precip
1    Січ      38
2    Лют      36
3    Бер      34
4    Кві      36
5    Тра      46
6    Чер      56
7    Лип      60
8    Сер      48
9    Вер      36
10   Жов      36
11   Лис      44
12   Гру      44

In [12]:
print(df[df["avg_temp"] > 15])

  month  avg_temp  precip
5   Тра        16      46
6   Чер        19      56
7   Лип        21      60
8   Сер        20      48

In [13]:
print(
    df[
        (df["avg_temp"] > 10) &
        (df["precip"] > 50)
    ]
)

  month  avg_temp  precip
6   Чер        19      56
7   Лип        21      60

In [14]:
print(
    df[
        (df["avg_temp"] < 0) |
        (df["precip"] > 80)
    ]
)

   month  avg_temp  precip
1    Січ        -5      38
2    Лют        -4      36
12   Гру        -3      44

In [15]:
df["avg_temp_f"] = df["avg_temp"] * 9 / 5 + 32

print(df)

   month  avg_temp  precip  avg_temp_f
1    Січ        -5      38        23.0
2    Лют        -4      36        24.8
3    Бер         1      34        33.8
4    Кві        10      36        50.0
5    Тра        16      46        60.8
6    Чер        19      56        66.2
7    Лип        21      60        69.8
8    Сер        20      48        68.0
9    Вер        14      36        57.2
10   Жов         8      36        46.4
11   Лис         1      44        33.8
12   Гру        -3      44        26.6

In [16]:
average_precip = df["precip"].mean()

df["is_wet"] = df["precip"] > average_precip

print(df)

   month  avg_temp  precip  avg_temp_f  is_wet
1    Січ        -5      38        23.0   False
2    Лют        -4      36        24.8   False
3    Бер         1      34        33.8   False
4    Кві        10      36        50.0   False
5    Тра        16      46        60.8    True
6    Чер        19      56        66.2    True
7    Лип        21      60        69.8    True
8    Сер        20      48        68.0    True
9    Вер        14      36        57.2   False
10   Жов         8      36        46.4   False
11   Лис         1      44        33.8    True
12   Гру        -3      44        26.6    True

In [17]:
def get_season(month_number):
    if month_number in [12, 1, 2]:
        return "зима"
    elif month_number in [3, 4, 5]:
        return "весна"
    elif month_number in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"


df["season"] = df.index.to_series().apply(get_season)

print(df)

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -5      38        23.0   False   зима
2    Лют        -4      36        24.8   False   зима
3    Бер         1      34        33.8   False  весна
4    Кві        10      36        50.0   False  весна
5    Тра        16      46        60.8    True  весна
6    Чер        19      56        66.2    True   літо
7    Лип        21      60        69.8    True   літо
8    Сер        20      48        68.0    True   літо
9    Вер        14      36        57.2   False  осінь
10   Жов         8      36        46.4   False  осінь
11   Лис         1      44        33.8    True  осінь
12   Гру        -3      44        26.6    True   зима