In [1]:
import numpy as np
import pandas as pd

orders = pd.DataFrame([
    {"дата": "2026-09-01", "товар": "Навушники", "місто": "Полтава",        "ціна": 700,        "кількість": 4},
    {"дата": "2026-09-02", "товар": "Навушники", "місто": " Полтава ",      "ціна": "700 грн",   "кількість": 5},
    {"дата": "2026-09-03", "товар": "Навушники", "місто": "ПОЛТАВА",        "ціна": 720,        "кількість": np.nan},
    {"дата": "2026-09-04", "товар": "Навушники", "місто": "Полтава",        "ціна": "680 грн",   "кількість": 3},
    {"дата": "2026-09-05", "товар": "Навушники", "місто": "Полтава",        "ціна": 710,        "кількість": np.nan},
    {"дата": "2026-09-06", "товар": "Навушники", "місто": "ПОЛТАВА",        "ціна": 690,        "кількість": 4},
    {"дата": "2026-09-07", "товар": "Навушники", "місто": "Полтава",        "ціна": 5600,       "кількість": 4},
    {"дата": "2026-09-07", "товар": "Навушники", "місто": "Полтава",        "ціна": 5600,       "кількість": 4},
])

print("Брудний набір даних:")
display(orders)

Брудний набір даних:

         дата      товар      місто     ціна  кількість
0  2026-09-01  Навушники    Полтава      700        4.0
1  2026-09-02  Навушники   Полтава   700 грн        5.0
2  2026-09-03  Навушники    ПОЛТАВА      720        NaN
3  2026-09-04  Навушники    Полтава  680 грн        3.0
4  2026-09-05  Навушники    Полтава      710        NaN
5  2026-09-06  Навушники    ПОЛТАВА      690        4.0
6  2026-09-07  Навушники    Полтава     5600        4.0
7  2026-09-07  Навушники    Полтава     5600        4.0

In [2]:
print("Кількість пропусків:")
print(orders.isna().sum())

Кількість пропусків:
дата         0
товар        0
місто        0
ціна         0
кількість    2
dtype: int64

In [3]:
median_quantity = orders["кількість"].median()

print("Медіана кількості:", median_quantity)

orders["кількість"] = orders["кількість"].fillna(median_quantity)

print("Після заповнення пропусків:")
display(orders)

Медіана кількості: 4.0
Після заповнення пропусків:

         дата      товар      місто     ціна  кількість
0  2026-09-01  Навушники    Полтава      700        4.0
1  2026-09-02  Навушники   Полтава   700 грн        5.0
2  2026-09-03  Навушники    ПОЛТАВА      720        4.0
3  2026-09-04  Навушники    Полтава  680 грн        3.0
4  2026-09-05  Навушники    Полтава      710        4.0
5  2026-09-06  Навушники    ПОЛТАВА      690        4.0
6  2026-09-07  Навушники    Полтава     5600        4.0
7  2026-09-07  Навушники    Полтава     5600        4.0

In [4]:
print("Кількість повних дублікатів:")
print(orders.duplicated().sum())

print("\nДублікати:")
display(orders[orders.duplicated()])

Кількість повних дублікатів:
1

Дублікати:

         дата      товар    місто  ціна  кількість
7  2026-09-07  Навушники  Полтава  5600        4.0

In [5]:
print("Кількість дублікатів за датою та товаром:")
print(orders.duplicated(subset=["дата", "товар"]).sum())

display(orders[orders.duplicated(subset=["дата", "товар"], keep=False)])

Кількість дублікатів за датою та товаром:
1

         дата      товар    місто  ціна  кількість
6  2026-09-07  Навушники  Полтава  5600        4.0
7  2026-09-07  Навушники  Полтава  5600        4.0

In [6]:
orders = orders.drop_duplicates(subset=["дата", "товар"])

print("Кількість рядків після видалення дубліката:", len(orders))

display(orders)

Кількість рядків після видалення дубліката: 7

         дата      товар      місто     ціна  кількість
0  2026-09-01  Навушники    Полтава      700        4.0
1  2026-09-02  Навушники   Полтава   700 грн        5.0
2  2026-09-03  Навушники    ПОЛТАВА      720        4.0
3  2026-09-04  Навушники    Полтава  680 грн        3.0
4  2026-09-05  Навушники    Полтава      710        4.0
5  2026-09-06  Навушники    ПОЛТАВА      690        4.0
6  2026-09-07  Навушники    Полтава     5600        4.0

In [7]:
orders["ціна"] = (
    orders["ціна"]
    .astype(str)
    .str.replace(" грн", "", regex=False)
    .astype(float)
)

print("Тип даних ціни:")
print(orders["ціна"].dtype)

display(orders)

Тип даних ціни:
float64

         дата      товар      місто    ціна  кількість
0  2026-09-01  Навушники    Полтава   700.0        4.0
1  2026-09-02  Навушники   Полтава    700.0        5.0
2  2026-09-03  Навушники    ПОЛТАВА   720.0        4.0
3  2026-09-04  Навушники    Полтава   680.0        3.0
4  2026-09-05  Навушники    Полтава   710.0        4.0
5  2026-09-06  Навушники    ПОЛТАВА   690.0        4.0
6  2026-09-07  Навушники    Полтава  5600.0        4.0

In [8]:
orders["місто"] = orders["місто"].str.strip().str.lower()

print("Унікальні назви міст після очищення:")
print(orders["місто"].unique())

Унікальні назви міст після очищення:
['полтава']

In [9]:
orders["місто"] = orders["місто"].replace({
    "полтава": "Полтава"
})

print("Унікальні назви міст:")
print(orders["місто"].unique())

display(orders)

Унікальні назви міст:
['Полтава']

         дата      товар    місто    ціна  кількість
0  2026-09-01  Навушники  Полтава   700.0        4.0
1  2026-09-02  Навушники  Полтава   700.0        5.0
2  2026-09-03  Навушники  Полтава   720.0        4.0
3  2026-09-04  Навушники  Полтава   680.0        3.0
4  2026-09-05  Навушники  Полтава   710.0        4.0
5  2026-09-06  Навушники  Полтава   690.0        4.0
6  2026-09-07  Навушники  Полтава  5600.0        4.0

In [10]:
q1 = orders["ціна"].quantile(0.25)
q3 = orders["ціна"].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

print("Q1 =", q1)
print("Q3 =", q3)
print("IQR =", iqr)
print("Нижня межа =", lower)
print("Верхня межа =", upper)

Q1 = 695.0
Q3 = 715.0
IQR = 20.0
Нижня межа = 665.0
Верхня межа = 745.0

In [11]:
outliers = orders[
    (orders["ціна"] < lower) |
    (orders["ціна"] > upper)
]

print("Викиди:")
display(outliers)

Викиди:

         дата      товар    місто    ціна  кількість
6  2026-09-07  Навушники  Полтава  5600.0        4.0

In [12]:
orders_clean = orders[
    (orders["ціна"] >= lower) &
    (orders["ціна"] <= upper)
].copy()

print("Очищений набір:")
display(orders_clean)

Очищений набір:

         дата      товар    місто   ціна  кількість
0  2026-09-01  Навушники  Полтава  700.0        4.0
1  2026-09-02  Навушники  Полтава  700.0        5.0
2  2026-09-03  Навушники  Полтава  720.0        4.0
3  2026-09-04  Навушники  Полтава  680.0        3.0
4  2026-09-05  Навушники  Полтава  710.0        4.0
5  2026-09-06  Навушники  Полтава  690.0        4.0

In [ ]:
1. Чому середнє може спотворити стандартне відхилення?

Заповнення пропуску середнім може зменшити або змінити стандартне відхилення, оскільки пропущене значення замінюється значенням, яке знаходиться саме в центрі набору. У результаті штучно зменшується розкид даних. Медіана є більш стійкою до викидів і нетипових значень, тому в цьому наборі вона є кращим варіантом.

2. Різниця між duplicated() без subset і з subset

duplicated() без subset шукає рядки, у яких повністю збігаються всі стовпці. Якщо вказати subset, перевіряються тільки вибрані стовпці. Наприклад, два замовлення можуть відрізнятися ціною або кількістю, але мати однакову дату та товар. Тоді при перевірці за subset=["дата", "товар"] вони будуть вважатися дубльованими.

3. Чому не можна автоматично видаляти всі значення поза IQR?

Значення за межами IQR не обов'язково є помилками. Це може бути реальне рідкісне спостереження. Наприклад, клієнт справді міг зробити дуже велике замовлення. Тому IQR потрібно використовувати для виявлення підозрілих значень, а остаточне рішення про видалення потрібно приймати після аналізу предметної області.